# Generated by Django 5.0.7 on 2024-08-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0002_walk_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order_no', models.IntegerField()),
                ('picture_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
