# Generated by Django 5.0.7 on 2024-08-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0003_visitingpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitingpoint',
            name='km',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
