# Generated by Django 5.0.7 on 2024-08-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0004_visitingpoint_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitingpoint',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
